name: KaolaList Sync to Gitee ğŸ¨ğŸ”

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repo to Gitee
        uses: Yikun/gitee-mirror-action@master
        with:
          src: github/bitkoala
          dst: gitee/bitekaola
          static_list: "KaolaList"
          dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          debug: true
