name: KoalaHealth Sync to Gitee ğŸ¨ğŸ”

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repo to Gitee
        uses: Yikun/gitee-mirror-action@master
        with:
          src: github/bitkoala
          dst: gitee/bitekaola
          static_list: "koalahealth"
          # --- é‡ç‚¹ï¼šå»æ‰ dst_keyï¼Œæ”¹ç”¨ clone_style: https ---
          dst_token: ${{ secrets.GITEE_TOKEN }}
          clone_style: https
          force_update: true
          debug: true